# Generated by Django 2.2.3 on 2019-07-13 13:59

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20190713_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('cover', '430x360', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping'),
        ),
    ]
