# Generated by Django 2.2.3 on 2019-07-13 14:22

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_book_cropping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=image_cropping.fields.ImageCropField(blank=True, null=True, upload_to='books/covers/'),
        ),
    ]
