# Generated by Django 2.2.3 on 2019-07-14 06:25

from django.db import migrations, models
import home.validators


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20190714_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='books/pdfs/', validators=[home.validators.validate_file_size]),
        ),
    ]
