# Generated by Django 2.2.3 on 2019-07-14 05:40

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('newone', '0003_auto_20190714_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonemodel',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None),
        ),
    ]
